# Generated by Django 5.2 on 2025-05-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_token',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
