# Generated by Django 5.2 on 2025-05-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_first_name_userprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='git_username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
