# Generated by Django 5.2 on 2025-05-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicd', '0002_language_framework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='pull_request_branch',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='push_branch',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='repo',
        ),
        migrations.AddField(
            model_name='workflow',
            name='repo_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
