# Generated by Django 5.2 on 2025-05-11 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cicd', '0004_workflow_created_at_workflow_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='public',
        ),
    ]
