name: dautometor-django

on:
  push:
    branches:
      {%for branch  in  push_branches%}
        - {{ branch }}
        {%endfor%}
  pull_request:
    branches:
      {%for branch  in  pull_request_branches%}
        - {{ branch }}
        {%endfor%}
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
        
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: {{ version }}
            
            - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

            
            -name : SSh  To  Server
            uses: appleboy/scp-action@master
            with:
              host: ${{ varts.HOST }}
              username: ${{ vars.USERNAME }}
              key: ${{ vars.SSH_KEY }}
              port: 22
              source: "."
            
            - name: Deploy to server
            run: |
              ssh -i ${{ vars.SSH_KEY }} -p 22 ${{ vars.USERNAME }}@${{ vars.HOST }} << 'EOF'
                cd {{server_path}}
                git pull origin {{ branch }}
                source venv/bin/activate
                pip install -r requirements.txt
                python manage.py migrate
                python manage.py collectstatic --noinput
                sudo systemctl restart {{ service_name }}
                sudo systemctl restart nginx
              EOF
              